<a href="https://colab.research.google.com/github/Ghifarahadian/concurrent-activity-recognition/blob/master/CNNLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# this is a classic usage for google colab

import sys
import os.path as osp
import os
import gc
from google.colab import drive
drive.mount('/content/drive')
ROOT = osp.join('/content', 'drive', 'My Drive', 'OpportunityUCIDataset')
os.chdir(ROOT)

Mounted at /content/drive


In [ ]:
# this is used when running the code on the pc

import sys
import os
import gc

ROOT = os.path.join(os.getcwd(), 'OpportunityUCIDataset')
os.chdir(ROOT)
print(ROOT)

In [ ]:
import torch
import pandas as pd
import numpy as np
import glob

if torch.cuda.is_available():
    device = torch.device("cuda:0")  # you can continue going on here, like cuda:1 cuda:2....etc. 
    print("Running on the GPU")
else:
    device = torch.device("cpu")
    print("Running on the CPU")

Running on the GPU


In [ ]:
from torch.utils.data import Dataset, DataLoader

class OpportunityDatasetParsed(Dataset):
    def __init__(self, filenames):
        self.filenames = filenames
        
    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, index):
        filename = self.filenames[index]
        #print(filename)
        df = pd.read_csv(filename, header = 0)
        data = torch.FloatTensor(
            df.iloc[:, 0:15].values.astype('float'))
        label = torch.FloatTensor(
            df.iloc[99, 15:18].values.astype('float'))

        # data_row = self.data[index]
        # label_row = self.label[index]

        # # assign the data
        # self.data = torch.FloatTensor(
        #     df.iloc[:, 0:15].values.astype('float'))
        
        # # assign the label. Only one label for now
        # self.label = torch.FloatTensor(
        #     df.iloc[0, 15:18].values.astype('float'))

        return data, label

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import torch

In [ ]:
num_epochs = 20
batch_size = 1
learning_rate = 0.01

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv1d(1, 3, 3)
        self.conv2 = nn.Conv1d(3, 6, 3)
        self.conv3 = nn.Conv1d(6, 12, 3)
        self.conv4 = nn.Conv1d(12, 24, 3)
        self.pool = nn.MaxPool1d(2)
        self.lstm1 = nn.LSTM(168, 64)
        self.lstm2 = nn.LSTM(96, 96)
        self.lstm3 = nn.LSTM(96, 96)
        self.fc1 = nn.Linear(64, 16)
        self.fc2 = nn.Linear(16, 3)
        self.fc3 = nn.Linear(96, 64)
        
        self.lstmtemp = nn.LSTM(15, 8)
        self.fctemp = nn.Linear(8*100, 3)  # the output is only 3 anw lul


#     def forward(self, x):
#         x = F.relu(self.conv1(x), inplace=False)
#         #print(x.shape)
#         x = F.relu(self.conv2(x), inplace=False)
#         #print(x.shape)
#         x = F.relu(self.conv3(x), inplace=False)
#         #print(x.shape)
#         x = F.relu(self.conv4(x), inplace=False)
#         #print(x.shape)
#         x = x.view(-1, 1, 24 * 7)
#         #print(x.shape)

#         lstm_out1, h1 = self.lstm1(x)
#         #print(lstm_out1.shape)
#         x_out = self.fc1(lstm_out1[:, -1, :])
#         #print(x_out[:, -1, :].shape)
#         out1 = self.fc2(x_out)
#         #print(lstm_out1.shape)

#         # lstm_out2, h2 = self.lstm2(x - lstm_out1)
#         # out2 = self.fc2(lstm_out2[:, -1, :])

#         # lstm_out3, h3 = self.lstm3(x - lstm_out1 - lstm_out2)
#         # out3 = self.fc3(lstm_out3[:, -1, :])

#         return out1#, out2, out3

    def forward(self, x, h):
        #print(x.shape)

        x, _ = self.lstmtemp(x, h)
        #print(x.shape)
        x = x.contiguous().view(1, -1)
        #print(x.shape)
        out = self.fctemp(x)
        #print(out.shape)
        return out

    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = (weight.new(1, 100, 8).zero_().to(device),
                      weight.new(1, 100, 8).zero_().to(device))
        return hidden
            

weights = [1/4, 1, 1]
class_weights = torch.FloatTensor(weights)
#loss_function = nn.CrossEntropyLoss(weight=class_weights)
loss_function = nn.CrossEntropyLoss()

net = Net().to(device)
print(net)

optimizer = torch.optim.SGD(net.parameters(), lr=learning_rate)

Net(
  (conv1): Conv1d(1, 3, kernel_size=(3,), stride=(1,))
  (conv2): Conv1d(3, 6, kernel_size=(3,), stride=(1,))
  (conv3): Conv1d(6, 12, kernel_size=(3,), stride=(1,))
  (conv4): Conv1d(12, 24, kernel_size=(3,), stride=(1,))
  (pool): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (lstm1): LSTM(168, 64)
  (lstm2): LSTM(96, 96)
  (lstm3): LSTM(96, 96)
  (fc1): Linear(in_features=64, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=3, bias=True)
  (fc3): Linear(in_features=96, out_features=64, bias=True)
  (lstmtemp): LSTM(15, 8)
  (fctemp): Linear(in_features=800, out_features=3, bias=True)
)


In [ ]:
# to refresh

drive.flush_and_unmount()
drive.mount('/content/drive')
ROOT = osp.join('/content', 'drive', 'My Drive', 'OpportunityUCIDataset')
os.chdir(ROOT)

Mounted at /content/drive


In [ ]:
h

NameError: ignored

In [ ]:
data_train_files = glob.glob("dataset_parsed/train/*.csv")
data_test_files = glob.glob("dataset_parsed/test/*.csv")

net.train()
h = net.init_hidden(batch_size)

for epoch in range(num_epochs):
    print("Epoch " + str(epoch + 1))

    data_train = OpportunityDatasetParsed(data_train_files)

    dataloader_train = DataLoader(data_train, batch_size=batch_size,
                    shuffle=False)

    for data, labels in dataloader_train:
        optimizer.zero_grad()
        data, labels = data.to(device), labels.to(device)

        data = torch.reshape(data, (batch_size, -1, 15))
        #print(data.shape)

        label_1 = torch.reshape(labels[:, 0:1].long(), (-1,))
        
        output_1 = net(data, h)
        #print(output_1.shape)

        loss = loss_function(output_1, label_1)
        loss.backward()
        optimizer.step()

        print("Loss: {}".format(loss.item()))

    # Calculate Accuracy

Streaming output truncated to the last 5000 lines.
Loss: 1.0340957641601562
Loss: 0.5949702262878418
Loss: 0.6664013862609863
Loss: 0.7349691987037659
Loss: 0.536689817905426
Loss: 0.003318044124171138
Loss: 1.1718288660049438
Loss: 0.0009539344464428723
Loss: 0.5622801780700684
Loss: 0.004816952161490917
Loss: 0.07112734764814377
Loss: 0.38446998596191406
Loss: 0.2289406955242157
Loss: 0.10170328617095947
Loss: 0.001642546383664012
Loss: 0.5004194974899292
Loss: 0.2543288767337799
Loss: 0.0022446929942816496
Loss: 0.9346524477005005
Loss: 0.27839407324790955
Loss: 1.0170989036560059
Loss: 0.0003457663697190583
Loss: 0.0005382042727433145
Loss: 0.0002740246127359569
Loss: 0.007354802917689085
Loss: 0.001929447171278298
Loss: 0.3357199728488922
Loss: 0.763594388961792
Loss: 0.0182656142860651
Loss: 1.1688902378082275
Loss: 0.3221285045146942
Loss: 0.0005801424849778414
Loss: 1.1269322633743286
Loss: 0.5246845483779907
Loss: 0.004784919787198305
Loss: 0.4100571572780609
Loss: 0.087766215

In [ ]:
output_1

tensor([ 0.1042, -0.1701,  0.0515], device='cuda:0', grad_fn=<AddBackward0>)

In [ ]:
h = net.init_hidden(batch_size)
with torch.no_grad():
    print(filename)
    df = pd.read_csv(filename, header = 0)

    data_test = OpportunityDatasetParsed(data_test_files)

    dataloader_test = DataLoader(data_test, batch_size=batch_size,
                    shuffle=False)

    correct_1 = 0

    total_1 = 0

    # Iterate through test dataset
    for data, labels in dataloader_test:

        data, labels = data.to(device), labels.to(device)
        data = torch.reshape(data, (batch_size, -1, 15))
        #print(data.shape)

        label_1 = torch.reshape(labels[:, 0:1].long(), (-1,))



        output_1 = net(data, h)
        #print(output_1)

        _, predicted_1 = torch.max(output_1, 1)
        print(predicted_1)


        total_1 += label_1.size(0)


        correct_1 += (predicted_1 == label_1).sum()


    accuracy_1 = 100 * torch.true_divide(correct_1, total_1)

    print('Accuracy_1: {}'.format(accuracy_1))

dataset_parsed/test/S2-ADL4-4.csv
tensor([2], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([2], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([0], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([0], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1], device='cuda:0')
tensor([0], device='cuda:0')
tensor([1

In [ ]:
label_1

tensor([ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [ ]:
# clean the data
data_train_files = glob.glob("dataset/train/*.dat")
data_test_files = glob.glob("dataset/test/*.dat")

for filename in data_train_files:
#for filename in data_test_files:
    print(filename)
    data = pd.read_table(filename, sep = "\s+", header = None)

    # clean the data
    df = data[col_all].copy()
    del data
    gc.collect()
    df.columns = col_all_name

    df.dropna(inplace=True)
    df = df[(df["Locomotion"] != 0) &
            (df["LL_Right_Arm"] != 0) &
            (df["ML_Both_Arms"] != 0)]

    # remap the output as 0-indexing to make learning possible
    df["Locomotion"] = df["Locomotion"].map({1: 0, 2: 1, 4: 2, 5: 3})
    df["LL_Right_Arm"] = df["LL_Right_Arm"].map(
        {401: 0, 402: 1, 403: 2, 404: 3, 405: 4, 406: 5, 407: 6, 408: 7,
         409: 8, 410: 9, 411: 10, 412: 11, 413: 12})
    df["ML_Both_Arms"] = df["ML_Both_Arms"].map(
        {406516: 0, 406517: 1, 404516: 2, 404517: 3, 406520: 4, 404520: 5,
         406505: 6, 404505: 7, 406519: 8, 404519: 9, 406511: 10, 404511: 11,
         406508: 12, 404508: 13, 408512: 14, 407521: 15, 405506: 16})
    
    df[col_feature_name] = df[col_feature_name].apply(normalize, axis=1)
    
    file = filename.split("\\")[1][:-4]
    df.to_csv("dataset_cleaned/train_temp/" + file + ".csv")
    #df.to_csv("dataset_cleaned/test/" + file + ".csv", index=False)

dataset/train\S2-ADL2.dat


C:\Users\GHIFARIRAHAD\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: read_table is deprecated, use read_csv instead.
  


dataset/train\S2-ADL3.dat
dataset/train\S2-ADL4.dat
dataset/train\S3-ADL1.dat
dataset/train\S3-ADL2.dat
dataset/train\S3-ADL3.dat
dataset/train\S3-ADL4.dat
dataset/train\S4-ADL1.dat
dataset/train\S4-ADL2.dat
